apps/config/urls.py
from os import stat
from django.conf.urls import url,include
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from manage import get_env_variable
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'',include('main.urls')),
    # path('',views.index)
]

DJANGO_EXECUTION_ENVIRONMENT = get_env_variable('DJANGO_EXECUTION_ENVIRONMENT')
if DJANGO_EXECUTION_ENVIRONMENT == "LOCAL":
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/main/urls.py
from os import name
from django.conf.urls import url
from django.urls.conf import path
from . import views

urlpatterns = [
    path('',views.home,name='home'),
    path('addProduct/',views.addProduct,name='addProduct'),
    url(r'^load_product/$', views.load_product, name='amount'),
]

apps/main/models.py
from django.db import models
import os 
import uuid

# models created with this base will inherit created_date and modified_date automatically
class ProductModel(models.Model):


    def get_file_path(instance, filename):
        ext = filename.split('.')[-1]
        filename = "%s.%s" % (uuid.uuid4(), ext)
        return os.path.join('products_images/', filename)

    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    product_name = models.CharField(max_length=100)
    product_skd = models.CharField(max_length=50,unique=True)
    product_price = models.DecimalField(max_digits=5,decimal_places=2)
    product_stock = models.DecimalField(max_digits=5,decimal_places=2)
    product_desc = models.CharField(max_length=240)
    product_image = models.ImageField(upload_to = get_file_path)
    
    # def json_to_form(self):
    #     data = self.

    # class Meta:
        # abstract = True

apps/main/forms.py
from django import forms
from django.forms.models import ModelForm 
from .models import ProductModel
import os 
import uuid
class ProductAddForm(forms.ModelForm):
    product_name = forms.CharField(label='name', max_length=100)
    product_skd = forms.CharField(label='skd', max_length=50)
    product_price = forms.DecimalField(label='price',max_digits=5)
    product_stock = forms.DecimalField(label='stock',max_digits=5)
    product_desc = forms.CharField(label='desc',max_length=240)
    product_image = forms.ImageField(label='image',required=True) 
    class Meta:
        model = ProductModel
        fields = "__all__" 

apps/main/views.py
import json
from os import error, stat
from django.db.models.fields.files import ImageField
from django.http import request,QueryDict
from django.http.response import HttpResponse, JsonResponse
from django.shortcuts import render
from .models import ProductModel
from .forms import ProductAddForm

# Create your views here.
def home(request):
    return render(request,'main/home.html',context=None)

# Add product page
def addProduct(request):
        # if this is a POST request we need to process the form data

    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        # d = QueryDict(request.POST)
        # print(d)
        print(request.POST,request.FILES)
        # print(request.POST['data'].split('&'))
        
        form = ProductAddForm( data=request.POST,files=request.FILES)
        print(form.errors)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required 
            product_name = form.cleaned_data.get('product_name')
            product_skd = form.cleaned_data.get('product_skd')
            product_price = float(form.cleaned_data.get('product_price'))
            product_stock = float(form.cleaned_data.get('product_stock'))
            product_desc = form.cleaned_data.get('product_desc')
            product_image = form.cleaned_data.get('product_image')
            obj = ProductModel.objects.create( 
                                 product_name = product_name,  
                                 product_skd = product_skd,
                                 product_price = product_price,
                                 product_stock = product_stock,
                                 product_desc = product_desc,
                                 product_image = product_image 
                                 ) 
            obj.save() 
            print(obj)
            # form.save()
            return JsonResponse({"instance": list(ProductModel.objects.all().values())}, status=200)
        else:
            return JsonResponse({"error": list(form.errors.values())}, status=200)
            
    # if a GET (or any other method) we'll create a blank form
    else:
        form = ProductAddForm()
        
        
        # all_entries = ProductModel.objects.count()
        return render(request,'products/add_products.html',{'form': form,'current':'all_entries'})

# load data and send it to user
def load_product(request):
    if request.method == 'GET':
        total_per_page = 10
        response_data ={'data':'123456'}
        response_data['total'] = total_per_page
    return render(request,'products/products_grid.html',response_data)

apps/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
    <div class="container-fluid">
        <h1>Forbidden (403)</h1>
        <p>CSRF verification failed. Request aborted.</p>
    </div>
{% endblock content %}

apps/templates/base.html
{% extends 'bootstrap5/bootstrap5.html' %}
{% load bootstrap5 %}
{% load static %}
{% load fontawesome_5 %}


{% block bootstrap5_title %}
    {% block title %}
    {% endblock %} - django boilerplate App
{% endblock %}

{% block bootstrap5_extra_head %}
    <script src="//ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/global.css' %}"/>
    {% fontawesome_5_static %} 
    {% bootstrap_javascript %}
    {% block head %}        
    {% endblock %}
{% endblock %}

{% block bootstrap5_content %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand">Eshop</a>
        <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/addProduct/">add Product</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
      </ul>
      </div>
    <form class="d-flex">
      <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
  </div>
</nav>
    {% block content %}
    {% endblock %}
{% endblock %}

{% block bootstrap5_extra_script %}
    <script src="{% static 'js/global.js' %}"></script>
    {% block scripts %}
    {% endblock %}
{% endblock %}

apps/templates/bootstrap.html
{% extends 'bootstrap5/bootstrap5.html' %}

{% block bootstrap5_title %}{% block title %}{% endblock %}{% endblock %}

apps/templates/main/home.html
{% extends "base.html" %}
{% load bootstrap5 %}
{% load fontawesome_5 %}

{%load static%}
    {% comment %} <link rel="stylesheet" href="{% static 'css/global.css' %}"/> {% endcomment %}
{% block title %} Home
{% endblock %}

{% block head %}
{% endblock %}

{% block content %}

<div class="container centered-text">
    {% comment %} {% include "main/slider.html" %} {% endcomment %}
    <div>
    {% include "products/products_grid.html" %}
    </div>

    </div>
{% endblock %}

{% block scripts %}
{% endblock %}

apps/templates/main/slider.html
    <div class="container">
    <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      {% comment %} <img src="..." class="d-block w-100" alt="..."> {% endcomment %}
<svg class="bd-placeholder-img bd-placeholder-img-lg d-block w-100" width="400" height="200" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Third slide" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#555"></rect><text x="50%" y="50%" fill="#333" dy=".3em">Third slide</text></svg>
    </div>
    <div class="carousel-item">
      {% comment %} <img src="..." class="d-block w-100" alt="..."> {% endcomment %}
      <svg class="bd-placeholder-img bd-placeholder-img-lg d-block w-100" width="100" height="200" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Third slide" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#555"></rect><text x="50%" y="50%" fill="#333" dy=".3em">Third slide</text></svg>
    </div>
    <div class="carousel-item">
      {% comment %} <img src="..." class="d-block w-100" alt="..."> {% endcomment %}
      <svg class="bd-placeholder-img bd-placeholder-img-lg d-block w-100" width="400" height="200" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Third slide" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#555"></rect><text x="50%" y="50%" fill="#333" dy=".3em">Third slide</text></svg>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
    </div>

apps/templates/products/add_products.html
{% extends "base.html" %}
{% load bootstrap5 %}
{% load fontawesome_5 %}

{%load static%}
{% block title %} Home
{% endblock %}

{% block head %}
{% endblock %}

{% block content %}




<div class="container centered-text">
    {{current}}
    <form id="add_product_form" enctype="multipart/form-data">
        {% csrf_token %}
        {% comment %} {{ form.as_p }}  {% endcomment %}
        {% comment %} {{ form.as_ul }} {% endcomment %}
        <label for="id_product_name">Product name:</label>
        <input id="id_product_name" maxlength="100" value="1" name="product_name" required="" type="text">
        <label for="id_product_skd">Product skd:</label>
        <input id="id_product_skd" maxlength="50" value="1" name="product_skd" required="" type="text">
        <label for="id_product_price">Product price:</label>
        <input id="id_product_price" name="product_price" value="1" required="" step="0.01" type="number">
        <label for="id_product_stock">Product stock:</label>
        <input id="id_product_stock" name="product_stock" value="1" required="" step="0.01" type="number">
        <label for="id_product_desc">Product desc:</label>
        <input id="id_product_desc" maxlength="240" value="1" name="product_desc" required="" type="text">
        <label for="id_product_image">Product img:</label>
        <input accept="image/*" id="id_product_image" name="product_image" required="" type="file">
        <input id="add_product" type="submit" value="Submit">
    </form>
    <div id="message">


    </div>
</div>
{% endblock %}

{% block scripts %}
<script>
    $(document).on('submit', '#add_product_form', function (e) {
        e.preventDefault();
        //let productForm = document.getElementById('add_product_form');
        let productData = new FormData( $('#add_product_form').get(0));
        console.log(productData)
        $.ajax({
            type: 'POST',
            url: '/addProduct/',
            data: productData,
            processData: false,
            contentType: false,
            //{
            //    data: $("#add_product_form").serialize(),
            //    csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val()
            //},
            success: function (data) {
                $("#add_product_form").innerHTML = data;
                console.log(data)
            },
            error: function (data) {
                $("#add_product_form").innerHTML = data;
            }
        })
    });
</script>

{% endblock %}

apps/templates/products/products_grid.html
<div class="jumbotron">
    <h1 class="display-3">Products</h1>
    
    {% comment %} {% for i in response_data.data|make_list %}
        {{ i }}
    {% endfor %} {% endcomment %}


{% for contact in page_obj %}
    {# Each "contact" is a Contact model object. #}
    {{ contact.full_name|upper }}<br>
    ...
{% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>


    <p class="lead">Jumbo helper text</p>
    <hr class="my-2">
    <p>More info</p>
    <p class="lead">
        <a class="btn btn-primary btn-lg" href="Jumbo action link" role="button">Jumbo action name</a>
    </p>
</div>